Support for hugo modules
chabad360/hugo-gh-pages pull request #17
Opened 2020-10-25 18:06 UTC by EricStG

Added go in the docker image via the Dockerfile & added `hugo mod get` to the docker entrypoint.

Closes #16

2020-10-25 19:58 UTC, chabad360 commented
Looks good, do you think you can run a quick test to make sure it works?

2020-10-25 19:59 UTC, EricStG commented
Already did: https://github.com/EricStG/esg.dev/runs/1305574540?check_suite_focus=true

2020-10-28 14:47 UTC, chabad360 requested changes

2020-10-28 14:47 UTC, chabad360 commented on Dockerfile
> +RUN apk add --update --no-cache openssl git go && \
This needs to be put in [chabad360/hugo-actions](https://github.com/chabad360/hugo-actions).

2020-10-28 14:55 UTC, chabad360 approved these changes

2020-10-28 14:55 UTC, merged